---
title: Compiler-Fehler CS0156 | Microsoft-Dokumentation
ms.date: 2015-07-20
ms.prod: .net
ms.technology:
- devlang-csharp
ms.topic: article
f1_keywords:
- CS0156
dev_langs:
- CSharp
helpviewer_keywords:
- CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
caps.latest.revision: 9
author: BillWagner
ms.author: wiwagn
translation.priority.ht:
- de-de
- es-es
- fr-fr
- it-it
- ja-jp
- ko-kr
- ru-ru
- zh-cn
- zh-tw
translation.priority.mt:
- cs-cz
- pl-pl
- pt-br
- tr-tr
translationtype: Machine Translation
ms.sourcegitcommit: a06bd2a17f1d6c7308fa6337c866c1ca2e7281c0
ms.openlocfilehash: 2d8cdfbea9e023dde6326791fb7f8c91725c42b7
ms.lasthandoff: 03/13/2017

---
# <a name="compiler-error-cs0156"></a>Compilerfehler CS0156
In einer finally-Klausel, die in der nächsten einschließenden catch-Klausel geschachtelt ist, ist keine throw-Anweisung ohne Argumente zulässig.  
  
 Ein [auslösen](../../csharp/language-reference/keywords/throw.md) -Anweisung ohne Parameter kann nur angezeigt werden, eine **catch** -Klausel, die keine Parameter akzeptiert.  
  
 Weitere Informationen finden Sie unter [Exception Handling Statements](../../csharp/language-reference/keywords/exception-handling-statements.md) und [Ausnahmen und Ausnahmebehandlung](../../csharp/programming-guide/exceptions/index.md).  
  
 Im folgenden Beispiel wird CS0156 generiert:  
  
```  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
