---
title: Die Throw-Anweisung kann außerhalb einer Catch-Anweisung oder innerhalb einer Finally-Anweisung den Operanden nicht auslassen.
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 17185ec328cecc29560b28e878682005e2a8a9e8
ms.sourcegitcommit: 0888d7b24f475c346a3f444de8d83ec1ca7cd234
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 12/22/2018
ms.locfileid: "53768114"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a>Die Throw-Anweisung kann außerhalb einer Catch-Anweisung oder innerhalb einer Finally-Anweisung den Operanden nicht auslassen.
`Throw` -Anweisungen außerhalb einer `Catch` -Anweisung müssen den Namen eines Ausnahmeobjekts angeben.  
  
 **Fehler-ID:** BC30666  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
1.  Geben Sie den Namen eines von `System.Exception`abgeleiteten Ausnahmeobjekts an.  
  
2.  Strukturieren Sie den Code neu, damit sich die `Throw` -Anweisung innerhalb eines `Catch` -Blocks befindet.  
  
## <a name="see-also"></a>Siehe auch  
 [Throw-Anweisung](../../visual-basic/language-reference/statements/throw-statement.md)  
 [Try...Catch...Finally-Anweisung](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [Ausnahmeklasse in Visual Basic](https://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [Ausnahmen- und Fehlerbehandlung in Visual Basic](https://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
