---
title: "&#39; Throw &#39; Anweisung kann nicht außerhalb Operanden nicht auslassen einer &#39; Catch &#39; -Anweisung oder innerhalb einer &#39; Schließlich &#39; Anweisung"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords: BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
caps.latest.revision: "8"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 5fa3be0ca47a4158b3abeef9801148e3f19d3b36
ms.sourcegitcommit: c0dd436f6f8f44dc80dc43b07f6841a00b74b23f
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 01/19/2018
---
# <a name="39throw39-statement-cannot-omit-operand-outside-a-39catch39-statement-or-inside-a-39finally39-statement"></a>&#39; Throw &#39; Anweisung kann nicht außerhalb Operanden nicht auslassen einer &#39; Catch &#39; -Anweisung oder innerhalb einer &#39; Schließlich &#39; Anweisung
`Throw` -Anweisungen außerhalb einer `Catch` -Anweisung müssen den Namen eines Ausnahmeobjekts angeben.  
  
 **Fehler-ID:** BC30666  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
1.  Geben Sie den Namen eines von `System.Exception`abgeleiteten Ausnahmeobjekts an.  
  
2.  Strukturieren Sie den Code neu, damit sich die `Throw` -Anweisung innerhalb eines `Catch` -Blocks befindet.  
  
## <a name="see-also"></a>Siehe auch  
 [Throw-Anweisung](../../visual-basic/language-reference/statements/throw-statement.md)  
 [Try...Catch...Finally-Anweisung](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [Ausnahmeklasse in Visual Basic](http://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [Ausnahmen- und Fehlerbehandlung in Visual Basic](http://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
