---
title: 'Vorgehensweise: Behandeln einer Ausnahme mit try/catch (C#-Programmierhandbuch)'
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: 74503c510007b132a7bbb14da7eade4c379b2179
ms.sourcegitcommit: 3c1c3ba79895335ff3737934e39372555ca7d6d0
ms.translationtype: HT
ms.contentlocale: de-DE
ms.lasthandoff: 09/06/2018
ms.locfileid: "43856577"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="53216-102">Gewusst wie: Behandeln einer Ausnahme mit try/catch (C#-Programmierhandbuch)</span><span class="sxs-lookup"><span data-stu-id="53216-102">How to: Handle an Exception Using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="53216-103">Ein [try/catch](../../../csharp/language-reference/keywords/try-catch.md)-Block soll von Arbeitscode generierte Ausnahmen abfangen und verarbeiten.</span><span class="sxs-lookup"><span data-stu-id="53216-103">The purpose of a [try-catch](../../../csharp/language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="53216-104">Einige Ausnahmen können in einem `catch`-Block verarbeitet werden, und das Problem kann behoben werden, ohne dass die Ausnahme erneut ausgelöst wird. Allerdings können Sie meistens nur sicherstellen, dass die passende Ausnahme ausgelöst wird.</span><span class="sxs-lookup"><span data-stu-id="53216-104">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="53216-105">Beispiel</span><span class="sxs-lookup"><span data-stu-id="53216-105">Example</span></span>  
 <span data-ttu-id="53216-106">In diesem Beispiel ist <xref:System.IndexOutOfRangeException> nicht die passendste Ausnahme: Für diese Methode ist <xref:System.ArgumentOutOfRangeException> sinnvoller, da der Fehler durch die Übergabe des Arguments `index` des Aufrufers verursacht wird.</span><span class="sxs-lookup"><span data-stu-id="53216-106">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/how-to-handle-an-exception-using-try-catch_1.cs)]  
  
## <a name="comments"></a><span data-ttu-id="53216-107">Kommentare</span><span class="sxs-lookup"><span data-stu-id="53216-107">Comments</span></span>  
 <span data-ttu-id="53216-108">Der Code, der eine Ausnahme auslöst, ist im `try`-Block eingeschlossen.</span><span class="sxs-lookup"><span data-stu-id="53216-108">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="53216-109">Eine `catch`-Anweisung wird direkt danach hinzugefügt, um `IndexOutOfRangeException` zu verarbeiten, falls dies auftritt.</span><span class="sxs-lookup"><span data-stu-id="53216-109">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="53216-110">Der `catch`-Block verarbeitet `IndexOutOfRangeException` und löst stattdessen die passendere Ausnahme `ArgumentOutOfRangeException` aus.</span><span class="sxs-lookup"><span data-stu-id="53216-110">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="53216-111">Um dem Aufrufer so viele Informationen wie möglich bereitzustellen, können Sie die ursprüngliche Ausnahme auf <xref:System.Exception.InnerException%2A> der neuen Ausnahme festlegen.</span><span class="sxs-lookup"><span data-stu-id="53216-111">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="53216-112">Da die Eigenschaft <xref:System.Exception.InnerException%2A> [schreibgeschützt](../../../csharp/language-reference/keywords/readonly.md) ist, müssen Sie sie im Konstruktor der neuen Ausnahme zuweisen.</span><span class="sxs-lookup"><span data-stu-id="53216-112">Because the <xref:System.Exception.InnerException%2A> property is [readonly](../../../csharp/language-reference/keywords/readonly.md), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="53216-113">Siehe auch</span><span class="sxs-lookup"><span data-stu-id="53216-113">See Also</span></span>

- [<span data-ttu-id="53216-114">C#-Programmierhandbuch</span><span class="sxs-lookup"><span data-stu-id="53216-114">C# Programming Guide</span></span>](../../../csharp/programming-guide/index.md)  
- [<span data-ttu-id="53216-115">Ausnahmen und Ausnahmebehandlung</span><span class="sxs-lookup"><span data-stu-id="53216-115">Exceptions and Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/index.md)  
- [<span data-ttu-id="53216-116">Ausnahmebehandlung</span><span class="sxs-lookup"><span data-stu-id="53216-116">Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/exception-handling.md)
